### ISSUE TITLE
Can't Add New Contact

### ISSUE THREAD

**Issue by ChrisTimcke** [AnthonyKon/Tafe19S101#4]
Set up contactDetails class and view but when I try to add a contact nothing happens

**Comment by ChrisTimcke** [comment]
Asked KT and he said it seems that the primary key is not auto generating as it should, there wasn't a solution that we could find so I'm going to redownload the project and hope not to get the same problem

**Comment by JarradStawiarski** [comment]
Try copying your folder to C/Temp and then running it

**Comment by robbie-Benson** [comment]
For reference you could look at one of the existing ones as they all work.

**Comment by ChrisTimcke** [comment]
I've copy pasted everything relevent to the new project and it's now working perfectly.
Thanks guys
